#!/bin/sh

#set -e

Debug ()
{
	for _PARAMETER in ${LIVE_BOOT_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-boot.debug|debug)
				LIVE_BOOT_DEBUG="true"
				;;
		esac
	done

	case "${LIVE_BOOT_DEBUG}" in
		true)
			;;

		*)
			return 0
			;;
	esac

	# Write the trace output
	set -x
}


live_debug_log ()
{
	# if $1 starts with 'live-boot:' then also drop a message to the kernel log
	if [ "${1}" = "${1#live-boot:}" ]; then
		echo "<7>live-boot: $1" > /dev/kmsg
	fi
	echo "${1}" >> /run/live/boot-live.log
}

