#!/bin/sh

#set -e

Remove_persistence ()
{
	live_debug_log "2010-remove-persistence: Remove_persistence BEGIN"
	for _PARAMETER in ${LIVE_BOOT_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-boot.persistence-remove=*|persistence-remove=*)
				LIVE_PERSISTENCE_REMOVE="${_PARAMETER#*persistence-remove=}"
				;;

			live-boot.persistence-remove|persistence-remove)
				LIVE_PERSISTENCE_REMOVE="true"
				;;
		esac
	done

	case "${LIVE_PERSISTENCE_REMOVE}" in
		true)
			;;

		*)
			live_debug_log "2010-remove-persistence: Remove_persistence END"
			return 0
			;;
	esac

	# Remove persistence
	live_debug_log "    Removing everything from /run/live/persistence except persistence.conf"
	cd /run/live/overlay && find . -not -name 'persistence.conf' | xargs rm -rf

	live_debug_log "2010-remove-persistence: Remove_persistence END"
}
